# Generated by Django 5.2.1 on 2026-05-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_condition_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldrule',
            name='condition',
        ),
        migrations.AddField(
            model_name='fieldrule',
            name='editable_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editable_rules', to='workflows.workflowcondition'),
        ),
        migrations.AddField(
            model_name='fieldrule',
            name='required_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_rules', to='workflows.workflowcondition'),
        ),
        migrations.AddField(
            model_name='fieldrule',
            name='visibility_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_rules', to='workflows.workflowcondition'),
        ),
    ]
