# Generated by Django 5.2.1 on 2026-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_fieldrule_python_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
